// This file is auto-generated by scripts/optimize-images.js. Do not edit manually.
export const OPTIMIZED_IMAGES: Record<string, number[]> = {
  'images/author.webp': [400, 800],
  'images/book-longest-nights.webp': [400, 800, 1200],
  'images/book-lust-love-memories.webp': [400, 800, 1200],
  'images/poem-art.webp': [400, 800, 1200],
  'images/poem-flower.webp': [400, 800, 1200],
  'images/poem-page.webp': [400, 800, 1200],
  'images/working.webp': [400, 800, 1200]
};
